FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /src
COPY Matrix.sln ./
COPY Matrix/Matrix.csproj Matrix/
COPY Matrix.Framework/Matrix.Framework.csproj Matrix.Framework/
COPY Matrix.Web/Matrix.Web.csproj Matrix.Web/
COPY Matrix.Web.Business/Matrix.Web.Business.csproj Matrix.Web.Business/
RUN dotnet restore "Matrix.Web/Matrix.Web.csproj"
COPY . .
WORKDIR /src/Matrix.Web
RUN dotnet build "Matrix.Web.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Matrix.Web.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Matrix.Web.dll"]