FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /src
COPY Matrix.sln ./
COPY Matrix/Matrix.csproj Matrix/
COPY Matrix.Framework/Matrix.Framework.csproj Matrix.Framework/
COPY Matrix.Agent.Journal/Matrix.Agent.Journal.csproj Matrix.Agent.Journal/
COPY Matrix.Agent.Journal.Business/Matrix.Agent.Journal.Business.csproj Matrix.Agent.Journal.Business/
COPY Matrix.Agent.Journal.Database/Matrix.Agent.Journal.Database.csproj Matrix.Agent.Journal.Database/
COPY Matrix.Agent.Journal.Model/Matrix.Agent.Journal.Model.csproj Matrix.Agent.Journal.Model/
RUN dotnet restore "Matrix.Agent.Journal/Matrix.Agent.Journal.csproj"
COPY . .
WORKDIR /src/Matrix.Agent.Journal
RUN dotnet build "Matrix.Agent.Journal.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Matrix.Agent.Journal.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Matrix.Agent.Journal.dll"]
