FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /src
COPY Matrix.sln ./
COPY Matrix/Matrix.csproj Matrix/
COPY Matrix.Framework/Matrix.Framework.csproj Matrix.Framework/
COPY Matrix.Agent.Directory/Matrix.Agent.Directory.csproj Matrix.Agent.Directory/
COPY Matrix.Agent.Directory.Business/Matrix.Agent.Directory.Business.csproj Matrix.Agent.Directory.Business/
COPY Matrix.Agent.Directory.Database/Matrix.Agent.Directory.Database.csproj Matrix.Agent.Directory.Database/
COPY Matrix.Agent.Directory.Model/Matrix.Agent.Directory.Model.csproj Matrix.Agent.Directory.Model/
RUN dotnet restore "Matrix.Agent.Directory/Matrix.Agent.Directory.csproj"
COPY . .
WORKDIR /src/Matrix.Agent.Directory
RUN dotnet build "Matrix.Agent.Directory.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Matrix.Agent.Directory.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Matrix.Agent.Directory.dll"]
